export const destinations = [
  {
    id: 1,
    name: "Indonesia",
    continent: "Asia",
    average_price: 1800,
    description: "Volcanoes and dream beaches.",
    time_zone: "UTC+7 (Jakarta)",
    language: "Indonesian",
    currency: "Indonesian Rupiah (IDR)",
    tourist_season: "April to October",
    theme: "exploration",
  },
  {
    id: 2,
    name: "Egypt",
    continent: "Africa",
    average_price: 1400,
    description: "Pyramids and ancient history.",
    time_zone: "UTC+2",
    language: "Arabic",
    currency: "Egyptian Pound (EGP)",
    tourist_season: "September to April",
    theme: "cultural",
  },
  {
    id: 3,
    name: "Maldives",
    continent: "Asia",
    average_price: 3200,
    description: "Overwater bungalows and blue lagoon.",
    time_zone: "UTC+5",
    language: "Dhivehi",
    currency: "Maldivian Rufiyaa (MVR)",
    tourist_season: "December to April",
    theme: "relax",
  },
  {
    id: 4,
    name: "Philippines",
    continent: "Asia",
    average_price: 1700,
    description: "Archipelago of 7000 islands.",
    time_zone: "UTC+8",
    language: "Filipino (Tagalog)",
    currency: "Philippine Peso (PHP)",
    tourist_season: "December to February",
    theme: "exploration",
  },
  {
    id: 5,
    name: "Seychelles",
    continent: "Africa",
    average_price: 2800,
    description: "Granite rocks and idyllic beaches.",
    time_zone: "UTC+4",
    language: "Seychellois Creole, French, English",
    currency: "Seychellois Rupee (SCR)",
    tourist_season: "April to October",
    theme: "relax",
  },
  {
    id: 6,
    name: "Iceland",
    continent: "Europe",
    average_price: 2100,
    description: "Northern lights and geysers.",
    time_zone: "UTC+0 (GMT)",
    language: "Icelandic",
    currency: "Icelandic Króna (ISK)",
    tourist_season: "June to August (summer), October to March (lights)",
    theme: "exploration",
  },
  {
    id: 7,
    name: "Japan",
    continent: "Asia",
    average_price: 2500,
    description: "Mix of tradition and modernity.",
    time_zone: "UTC+9",
    language: "Japanese",
    currency: "Yen (JPY)",
    tourist_season: "March to May (cherry blossoms), September to November",
    theme: "cultural",
  },
  {
    id: 8,
    name: "Italy",
    continent: "Europe",
    average_price: 1300,
    description: "Gastronomy, art, and Roman ruins.",
    time_zone: "UTC+1 (CET)",
    language: "Italian",
    currency: "Euro (EUR)",
    tourist_season: "April to June, September to October",
    theme: "cultural",
  },
  {
    id: 9,
    name: "Costa Rica",
    continent: "America",
    average_price: 1900,
    description: 'Exuberant nature and "Pura Vida".',
    time_zone: "UTC-6",
    language: "Spanish",
    currency: "Costa Rican Colón (CRC)",
    tourist_season: "December to April (dry season)",
    theme: "exploration",
  },
  {
    id: 10,
    name: "Greece",
    continent: "Europe",
    average_price: 1500,
    description: "Cycladic islands and mythology.",
    time_zone: "UTC+2 (EET)",
    language: "Greek",
    currency: "Euro (EUR)",
    tourist_season: "May to September",
    theme: "cultural",
  },
  {
    id: 11,
    name: "Peru",
    continent: "America",
    average_price: 2200,
    description: "Machu Picchu and Andean mountains.",
    time_zone: "UTC-5",
    language: "Spanish",
    currency: "Peruvian Sol (PEN)",
    tourist_season: "May to September",
    theme: "exploration",
  },
  {
    id: 12,
    name: "Morocco",
    continent: "Africa",
    average_price: 900,
    description: "Colorful souks and Sahara desert.",
    time_zone: "UTC+1",
    language: "Arabic, Berber",
    currency: "Moroccan Dirham (MAD)",
    tourist_season: "March to May, September to November",
    theme: "cultural",
  },
  {
    id: 13,
    name: "Australia",
    continent: "Oceania",
    average_price: 3500,
    description: "Surf, kangaroos, and Great Barrier Reef.",
    time_zone: "UTC+10 (Sydney)",
    language: "English",
    currency: "Australian Dollar (AUD)",
    tourist_season: "December to February (austral summer)",
    theme: "sporty",
  },
  {
    id: 14,
    name: "Canada",
    continent: "America",
    average_price: 2300,
    description: "Great national parks and Rockies.",
    time_zone: "UTC-5 (East) / UTC-8 (West)",
    language: "English, French",
    currency: "Canadian Dollar (CAD)",
    tourist_season: "June to September (summer)",
    theme: "sporty",
  },
  {
    id: 15,
    name: "Thailand",
    continent: "Asia",
    average_price: 1600,
    description: "Golden temples and street food.",
    time_zone: "UTC+7",
    language: "Thai",
    currency: "Baht (THB)",
    tourist_season: "November to February",
    theme: "cultural",
  },
  {
    id: 16,
    name: "New Zealand",
    continent: "Oceania",
    average_price: 3300,
    description: "Lord of the Rings landscapes.",
    time_zone: "UTC+12",
    language: "English, Maori",
    currency: "New Zealand Dollar (NZD)",
    tourist_season: "December to March (austral summer)",
    theme: "sporty",
  },
];
